#source common.sh
#
#if [ -z "${roboshop_rabbitmq_password}" ]; then
#echo " Variable roboshop_rabbitmq_password is not valid"
#exit
#fi
#
#print_head "Configuring Erlang YUM Repo"
#curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash &>>${LOG}
#status_check
#
#
#print_head "Configuring Rabbitmq Repo"
#curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash &>>${LOG}
#status_check
#
#
#print_head "Install Erlang and Rabbitmq"
#yum install erlang rabbitmq-server -y &>>${LOG}
#status_check
#
#print_head "Enable Rabbitmq"
#systemctl enable rabbitmq-server &>>${LOG}
#status_check
#
#
#print_head "start rabbitmq"
#systemctl start rabbitmq-server &>>${LOG}
#status_check
#
#
#print_head "Add Application user"
#rabbitmqctl list_users | grep roboshop &>>${LOG}
#if [ $? -ne 0 ]; then
#rabbitmqctl add_user roboshop ${roboshop_rabbitmq_password} &>>${LOG}
#fi
#status_check
#
#
#print_head "User tags"
#rabbitmqctl set_user_tags roboshop administrator &>>${LOG}
#status_check
#
#
#print_head "Add Permissions"
#rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" &>>${LOG}
#status_check


#item is just for denoting and it wouldn't do any harm to code
- name: Configure Yum Repos
  ansible.builtin.shell: curl -s {{ item }} |  bash
  loop:
    - https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
    - https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh

- name: Install Erlang & RabbitMQ
  ansible.builtin.yum:
    name:
      - erlang
      - rabbitmq-server
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Add Application User
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: "{{roboshop_rabbitmq_password}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator
