- name: Configure NodeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: APP Pre-req
  ansible.builtin.include_tasks: "app-prereq.yml"


- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Install NodeJS dependencies
  community.general.npm:
    path: /app
    state: latest


- name: SystemD setup
  ansible.builtin.include_tasks: "systemd.yml"

#import_tasks: "{{schema_type}}-schema.yml"
- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load



