#  PYTHON() {
#
#
#    print_head "Install PYTHON"
#    yum install python36 gcc python3-devel -y &>>${LOG}
#    status_check
#
#    APP_PREREQ
#
#    print_head "Download Dependencies"
#    cd /app &>>${LOG}
#    pip3.6 install -r requirements.txt &>>${LOG}
#    status_check
#
#    print_head "Update Password's in Service File"
#    sed -i -e "s/roboshop_rabbitmq_password/${roboshop_rabbitmq_password}/" ${script_location}/Files/${component}.service &>>{LOG}
#    status_check
#
#    SYSTEMD_SETUP
#
#    LOAD_SCHEMA
#
#
#
#  }


- name: Install Python 3
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: APP Pre-req
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: Download Python Dependencies
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.6

- name: SystemD Setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load




- name: Maven Build
  ansible.builtin.shell:  mvn clean package ;  mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: SystemD setup
  ansible.builtin.include_tasks: "systemd.yml"


#import_tasks: "{{schema_type}}-schema.yml"
- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load